### ISSUE TITLE
Checkbox does not appear into new issue form

### ISSUE THREAD

**Issue by Reeslo** [paginagmbh/redmine_silencer#10] opened 2015-08-06 09:12 UTC
I use the branch master

Environment:
  Redmine version                2.5.2.devel
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.1.12
  Environment                    production
  Database adapter               Mysql2

**Comment by Reeslo** [comment] 2015-09-05 14:16
Same issue into 3.0.4.stable up ?

**Comment by tofi86** [comment] 2015-11-22 18:35
This is a duplicate of issue #3 which I investigated today and unfortunately had to close it as impossible to implement. I'm sorry.

**Closed by tofi86** 2015-11-22 18:35 UTC
Labels: duplicate
